config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
    
  devise_for :users


  resources :users, only: [:show]

  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5, maximum: 100}
    validates :description, presence: true, length: {minimum: 5, maximum: 500}
    validates :keywords, presence: true, length: {minimum: 1, maximum: 100}

    has_many_attached :images

    belongs_to :user

    has_many :comments

    before_create :randomize_id
    private
    def randomize_id
      begin
        self.id = SecureRandom.random_number(1_000_000_000)
      end while User.where(id: self.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         has_many :posts
         has_many :comments

         before_create :randomize_id
         private
         def randomize_id
           begin
             self.id = SecureRandom.random_number(1_000_000_000)
           end while User.where(id: self.id).exists?
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post , notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:text, :user_id, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  before_action:authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json


  def show
    @comment = @post.comments.build
  end

  def myposts
    @posts = Post.all
  end

  

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, :user_id,images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.text_field :user_id , type:"hidden"%>
  </div>

  <div>
    <%= form.text_field :post_id , type:"hidden" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/home/about.html.erb
<h1>Welcome to our instagram clone using ruby on rails</h1>
<p>The contents of this page is static</p>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       
      <li class="nav-item">
        <%= link_to "Upload post", new_post_path,class:"nav-link" %>
      </li>
      
      <li class="nav-item">
        <%= link_to"About Page", home_about_path, class:"nav-link"%>
      </li>
      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to"View my profile", current_user, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to"Sign out", destroy_user_session_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to"Edit account", edit_user_registration_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to"View my Posts", posts_myposts_path, class:"nav-link"%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to"Sign up", new_user_registration_path, class:"nav-link"%>
      </li>
      <% end %>
    </ul>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
     
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384- J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvblyZFJoft +2mJbHaEWIdlv1910Yy5n3zV9zzTtml3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvblyZF.Joft +2mJbHaEWIdivI9IOYy5n3zV9zzTtml3UksdQRVvoxMfooño" crossorigin="anonymous"></s /script><script potstrap egrity="sha384-wfSDF2E50Y2D1uUdj003uMBJnjuUD4Ih7YwaYdliqfktj0Uod8GCExl30g8ifwB6" crossorigin="anonymous"></script>
    <!-- CSS only -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-betal/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-OevHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%=render "layouts/navbar"%>
    <%= yield %>
   

    <%=render "layouts/footer"%>

  </body>
</html>

app/views/posts/_form.html.erb
<div class:"col-xl-4 col-md-6 col-sm-8 col-10" style="margin: auto; background-color #f8f8f8, border-radius: 6px; padding: 15px">
<%= form_with(model: post) do |form| %>
  <h1>New post</h1>
  <div>
   <% invalid = post.errors.include?(:title)%>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title , class: "form-control"%>
    <% if invalid %>
    <p style="color:red">
      <%= post.errors.full_messages_for(:title).join(",")%>
      </p>
    <%end%>
  </div>
  <div>
   <%= form.text_field :user_id , type: "hidden", value: current_user.id%>
  
 </div>

  <div>
  <% invalid = post.errors.include?(:description)%>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description , class: "form-control" %>
    <% if invalid %>
    <p style="color:red">
      <%= post.errors.full_messages_for(:description).join(",")%>
      </p>
    <%end%>
  </div>

  <div>
  <% invalid = post.errors.include?(:description)%>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords , class: "form-control" %>
    <% if invalid %>
    <p style="color:red">
      <%= post.errors.full_messages_for(:keywords).join(",")%>
      </p>
    <%end%>
    <%= form.file_field :images, multiple:true %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary col-12"%>
  </div>
<% end %>
</div>

app/views/posts/_myposts.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
   
    <%= post.title %>
  </p>

  <p>
   
    <%= post.description %>
  </p>

  <p>
  
    <%= post.keywords %>
  </p>
  <p>
  
    <%= post.user.email %>
  </p>
  <p>
      <%= link_to "", post, class:"post-link" %>
    </p>
    <% post.images.each do |image|%>
      <%= image_tag(image, style: "object-fit: contain; width: 200px; height: 600px;")%>
    <%end%>

</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
   
    <%= post.title %>
  </p>

  <p>
   
    <%= post.description %>
  </p>

  <p>
  
    <%= post.keywords %>
  </p>
  <p>
  
    <%= post.user.email %>
  </p>
  <p>
      <%= link_to "", post, class:"post-link" %>
    </p>
    <% post.images.each do |image|%>
      <%= image_tag(image, style: "object-fit: contain; width: 200px; height: 600px;")%>
    <%end%>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>



<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
    
  <% end %>
</div>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>



<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <% if post.user.id == current_user.id %>

      <%= render post %>
    <% end %>
    
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row"><%= render "form", post: @post %></div>

<br>
 

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= link_to "Back to posts", posts_path %>
<% if user_signed_in? %>
<% if current_user.id == @post.user.id%>

 <div>
   <%= link_to "Edit this post", edit_post_path(@post) %> |

   <%= button_to "Destroy this post", @post, method: :delete %>
 </div>
<% end %>
<% end %>

<%= render "comments/form", comment: @comment %>
<% cnt = 0 %> 
<% size = @post.comments.count%>
<%= @post.comments.each do |comment|%>
  <%= comment.text %>
  <br> 
  <% cnt = cnt+1 %>
  <% if cnt > size %>
  <% break %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= @user.email %>